const initialValues = {
  firstName: '',
  lastName: '',
  birthPlace: '',
  birthDate: '',
  maritalStatus: '',
  mobile: '',
  tell1: '',
  tell2: '',
  email: '',
  clan: '',
  subclan: '',
  suldan: '',
  chief: '',
  currentLocation: '',
  currentRegion: '',
  currentDistrict: '',
  CurrentTown: '',
  address1: '',
  address2: '',
  locationRemarks: '',
  DestinationSameAsOrigin: '',
  destinationRegion: '',
  destinationDistrict: '',
  destinationTown: '',
  hostCountry: '',
  totalAbroadStay: '',
  dateOfReturn: '',
  reasonOfReturn: '',
  returnRemarks: '',
  EducationLevel: '',
  educationRemarks: '',
  profession: '',
  technicalSkills: '',
  businessSkills: '',
  farmingSkills: '',
  minorCase: '',
  victimOfTrafficking: '',
  isVulnerable: '',
  vulnerabilityFactors: '',
  vulnerabilityRemarks: '',
  caseRemarks: '',
}

export default initialValues
